### ISSUE TITLE
Combine Time with Count.

### ISSUE THREAD

**Issue by sheminasalam** [dkern/node-red-throttle#13]
Hi there, This could more likely be a feature request than a bug. I am looking for a node that can limit the number of messages in a particular time. For example 30 messages per 1 hour. We now can use the delay message for rate limiting but the problem is that in that node if we set 30 messages per 1 hour, it will sent one message per 2 minutes. I wish to have a node which can sent the first 30 messages as soon as it arrives in a set time frame and then either store or neglect the remaining messages. Throttle node is the closest to this function, thats why I have made this request.

**Comment by dkern** [comment]
Use this node in `block size` mode and set the limit to 30. Then use a `inject` node with a repeat of one hour to reset the counter. Done. ;)
